version: "3"

services:
  backend-prod:
    image: kimwonjin/oeuvre-server-prod:main
    container_name: backend-prod
    hostname: backend-prod
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-prod
    restart: always
    container_name: oeuvre-nginx-prod
    build:
      dockerfile: Dockerfile.prod
      context: ./config/nginx/prod
    ports:
      - "81:81"