version: "3"

services:
  backend-dev:
    image: kimwonjin/oeuvre-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "9090"
  backend-prod:
    image: kimwonjin/oeuvre-server-prod:main
    container_name: backend-prod
    hostname: backend-prod
    expose:
      - "8080"


  nginx:
    depends_on:
      - backend-dev
      - backend-prod
    restart: always
    container_name: oeuvre-nginx
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"