version: "3"

services:
  backend-dev:
    image: kimwonjin/oeuvre-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "9090"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"