# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy to Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Gradle packages  #속도를 빠르게
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      #
      - name: Grant execute permission for gradlew #권한
        run: chmod +x gradlew

      - name: Make application-dev.properties #환경변수 주입
        run: |
          touch ./src/main/resources/application-dev.properties
          echo "$PROPERTIES_DEV" > ./src/main/resources/application-dev.properties
          touch ./oeuvre-firebase.json
          echo "$FIREBASE_JSON" > ./oeuvre-firebase.json
        env:
          PROPERTIES_DEV: ${{ secrets.PROPERTIES_DEV }}
          FIREBASE_JSON: ${{ secrets.FIREBASE.JSON }}

      - name: Build with Gradle
        run: ./gradlew build -x test  #test 코드 빼고 돌리기


      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kimwonjin/oeuvre-server-dev


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.KEY_DEV }}
          script: mkdir -p ~/srv/ubuntu/oeuvre-dev

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: ~/srv/ubuntu/oeuvre-dev
          remote_host: ${{ secrets.HOST_DEV }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY_DEV }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.KEY_DEV }}
          script: |
            sh ~/srv/ubuntu/oeuvre-dev/config/scripts/deploy.sh
            sudo docker stop backend-dev
            sudo docker rm backend-dev
            sudo docker rmi $(sudo docker images -q)
            sudo docker-compose -f ~/srv/ubuntu/oeuvre-dev/docker-compose.yml pull
            sudo docker-compose -f ~/srv/ubuntu/oeuvre-dev/docker-compose.yml up --build -d
